services:
  - type: web
    name: qr-attendance-backend
    runtime: python3.9
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/selfies
    startCommand: |
    alembic upgrade head
    uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4 --limit-concurrency 1000 --limit-max-requests 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qr-attendance-db
          property: connectionString
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://new-attendance-form.vercel.app
      - key: WEB_CONCURRENCY
        value: "4"
      - key: MAX_WORKERS
        value: "4"

databases:
  - name: qr-attendance-db
    databaseName: qr_attendance_tnze
    user: qr_attendance_tnze_user










