services:
  - type: web
    name: qr-attendance-backend
    runtime: python3.9
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/selfies
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qr-attendance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://qr-frontend-attendancesystem.vercel.app

databases:
  - name: qr-attendance-db
    databaseName: qr_attendance
    user: qr_attendance_user






