"""fix_created_at_in_qr_sessions

Revision ID: 2b478ceed7f7
Revises: 67e0d31d3fef
Create Date: 2025-05-05 19:44:09.190352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b478ceed7f7'
down_revision: Union[str, None] = '67e0d31d3fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_sessions', 'qr_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_sessions', 'qr_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
