"""update_admin_user_model

Revision ID: 64e0d31d3fef
Revises: a24317005e43
Create Date: 2025-05-05 19:25:27.206247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e0d31d3fef'
down_revision: Union[str, None] = 'a24317005e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('admin_users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('admin_users', 'is_admin')
    # ### end Alembic commands ###
