"""remove_email_from_admin_user

Revision ID: 65e0d31d3fef
Revises: 64e0d31d3fef
Create Date: 2025-05-06 10:15:27.206247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e0d31d3fef'
down_revision: Union[str, None] = '64e0d31d3fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###
