"""description_of_changes

Revision ID: a24317005e43
Revises: add_missing_selfie_columns
Create Date: 2025-05-05 15:25:37.098090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a24317005e43'
down_revision: Union[str, None] = 'add_missing_selfie_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flagged_logs_id', table_name='flagged_logs')
    op.drop_table('flagged_logs')
    op.drop_index('ix_admin_users_id', table_name='admin_users')
    op.drop_index('ix_admin_users_username', table_name='admin_users')
    op.drop_table('admin_users')
    op.alter_column('attendances', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attendances', 'roll_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attendances', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attendances', 'section',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attendances', 'location_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('attendances', 'location_lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('attendances', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('attendances', 'created_at')
    op.alter_column('qr_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('qr_sessions', 'qr_image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_sessions', 'qr_image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('qr_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('attendances', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('attendances', 'session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendances', 'location_lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('attendances', 'location_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('attendances', 'section',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendances', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendances', 'roll_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendances', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('admin_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_users_pkey')
    )
    op.create_index('ix_admin_users_username', 'admin_users', ['username'], unique=True)
    op.create_index('ix_admin_users_id', 'admin_users', ['id'], unique=False)
    op.create_table('flagged_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flagged_logs_pkey')
    )
    op.create_index('ix_flagged_logs_id', 'flagged_logs', ['id'], unique=False)
    # ### end Alembic commands ###
